# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Greater San Diego Young Peoples AA'
tagline:             'Unity, Service, Recovery'
description:         ''
url:                 http://gsdypaa.github.io
baseurl:             ''

# About/contact
author:
  name:              GSDYPPA
  url:               http://gsdypaa.github.io
  email:             http://anonymus@gsdypaa.github.io

# Custom vars
version:             1.0.0

paginate:            2

gems:
  - octopress-paginate
